### PR TITLE
Marathon labels are not cleaned up

### PR DESCRIPTION
**Pull request by JayH5**
Consular puts Marathon app labels as k/v entries in Consular but it never removes old entries.

### CODE REVIEW

**Comment by JayH5** [comment]
Not using any fancy Consul k/v stuff for now- keeping it simple.

`main.py` is kind of ballooning and the current method of testing we're using is reaching its limits... might be time for some kind of a refactor soon.

Otherwise, ready for review.

**Comment by smn** [comment]
:+1:

**Comment by smn** [comment]
:+1:

**Pull request merged**
