### PR TITLE
Clean up debugging work from 19 October

### PR DESCRIPTION
**Pull request by JayH5**
Did a bunch of debugging work to get things working in a hurry.

### CODE REVIEW

**Comment by JayH5** [comment]
@miltontony @smn 
Actually made less of a mess yesterday than I thought. This is just a small cleanup, best reviewed commit-by-commit.

**Comment by smn** [comment]
:+1: from me, went through it commit by commit.

**Comment by miltontony** [comment]
:+1:

**Comment by JayH5** [comment]
Just gonna add another test that calls `purge_dead_apps()` as the coverage is missing.

**Pull request merged**
