### PR TITLE
Consular crashes if Consul k/v keys not found

### PR DESCRIPTION
**Pull request by JayH5**
Our testing is unfortunately not very thorough at the moment.

Since #30, things are broken as Consul returns a 404 when it can't find k/v keys and I didn't account for that :cry:

### CODE REVIEW

**Comment by JayH5** [comment]
I'm still debugging the fallout from #30 and unfortunately sideloader builds the tip of `develop` and not the latest release tag. So things are quite broken if you `sudo apt-get install consular`.

The current changes stop exceptions from happening but it doesn't seem like all the labels are being stored in Consul as they should be.

**Comment by smn** [comment]
:+1: once things calm down let's take a relook at the code base and see how we can refactor & remove some of the complexity that's recently grown organically.

**Comment by JayH5** [comment]
Sorry for additional changes. Just definitely do not want to decrease test coverage at the moment.

I have a branch I'm working on on the side that splits out the Marathon/Consul HTTP clients. I think it's a good first smaller refactor.

**Comment by smn** [comment]
:+1:

**Pull request merged**
