### PR TITLE
Services don't announce their correct host.

### PR DESCRIPTION
**Pull request by smn**
consul_by_hashicorp

This will become a problem once we do start querying DNS.

### CODE REVIEW

**Comment by smn** [comment]
``` bash
$ dig @qa-unicore -p 8600 gem-tz-25.service.consul SRV +short
1 1 8867 qa-unicore.node.dc1.consul.
```

Given the screenshot above it should return qa-unicore-x as the host.

**Comment by smn** [comment]
I suspect I need to change the setup to register things under the catalog instead of the agent as per https://www.consul.io/docs/guides/external.html

**Comment by smn** [comment]
@miltontony the tests pass but I'm going to run it locally to see how badly it breaks in QA first.

**Comment by smn** [comment]
@miltontony ready for review.

Biggest changes are:
1. service registration now needs a node-id
2. service registration happens via the catalog api, not the agent api.

**Comment by smn** [comment]
I'm not entirely convinced yet that this is what's needed tbh. The catalog is meant for external services, which these services which we're running are not.

I can use the Agent API but that assumes that the machine running the mesos-agent is also running consul. I thought I could avoid that using the catalog API but it turns out I can't since I'm having to specify  a `node` value for everything anyway. The node is supposed to be a consul node so there's the assumption there that a machine running mesos-slave is also running a consul node.

**Comment by smn** [comment]
Hm, actually going to go with this for now. The agent's way of going about it results in largely the same result. Rather test in production before deciding it's a bad idea.

**Comment by miltontony** [comment]
Hmm..so with this work?
The code looks fine, but your comment above leaves me not entirely sold that this will solve the problem. But I guess we'll just have to see
:+1:

**Comment by smn** [comment]
This managed to make consul quite unhappy.

**Pull request merged**
