### PR TITLE
Fix purging of app labels

### PR DESCRIPTION
**Pull request by JayH5**
Purging of app labels is broken - all the labels of the app are deleted.

### CODE REVIEW

**Comment by miltontony** [comment]
:+1:  great find!

**Comment by smn** [comment]
:cake:

**Comment by JayH5** [comment]
Just gonna add another test that calls `purge_dead_apps()` as the coverage is missing.

**Comment by JayH5** [comment]
Oh wait, never mind. Now I remember our test infrastructure doesn't support testing methods like that...

**Pull request merged**
